### ISSUE TITLE
Support "official" assets

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/seahorse#30]
- [x] Add `official: bool` to `AssetInfo`
- [x] Generate a key pair for signing official asset libraries and save the private key in RPass
- [x] Implement `load_official_asset_library`. This read a list of asset definitions from a file and mark the corresponding `AssetInfo` official _in memory only_. This is because official assets are intended to be static (loaded from a configuration file), but the static official assets may change between releases, so we don't want them persisted. The asset library file should be signed by a well-known public key, and the load should only succeed if the signature verifies.
- [x] Implement a utility for generating official asset libraries given a private key (CLI) and a list of asset definitions (can be hard-coded).

Depends on #29 
See EspressoSystems/cape-ui#37

**Comment by philippecamacho** [comment]
Should this be part of Deliverable2 @jbearer?

**Comment by jbearer** [comment]
Yep
