### ISSUE TITLE
`freeze` should not depend on `WalletBackend::get_public_key`

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/seahorse#37]
In some implementations (e.g. CAPE) `get_public_key` requires users to voluntarily register their encryption keys in a centralized database. Therefore, if `freeze` depends on this function, users can subvert freezing by refusing to register their encryption key in this database. They can still transfer assets by sharing their encryption key with conspirators on a private channel.

There are two places where `freeze` uses the encryption key:
1. It is a field of the input record openings (these are actually built when we _audit_ freezable records)
2. It is used to encrypt the owner memos for `freeze` transactions

For (1), the encryption key part of the record opening is not actually used to compute the record commitment, so it can be anything. For example, if we are unable to get the owner's encryption key from the backend, we can use a `UserPubKey` with the owner's address and our own encryption key as a placeholder.

For (2), owner memos aren't actually necessary for `freeze` transactions, since the owner can't do anything with the frozen records, anyways. Therefore, if we are unable to get the owner's encryption key, we can either encrypt the owner memos using our own key, or just omit them altogether. It doesn't really matter.

**Comment by philippecamacho** [comment]
Should this task be part of Deliverable 2?

**Comment by jbearer** [comment]
@philippecamacho yes it should, but I can't add it to the CAPE Deliverable 2 milestone since it's in this repository

**Comment by shenkeyao** [comment]
Update:
Constructing a `UserPubKey` with the owner's address and our own encryption key as a placeholder won't give us the asset records associated with the original `UserPubKey` since they have different encryption keys. Therefore, we need to modify the `asset_records` field of `RecordDatabase` to take `UserAddress` as the lookup key rather than `UserPubKey`.
